###　必須　Firebaseの認証情報を取得する。
POST https://identitytoolkit.googleapis.com/v1/accounts:signInWithPassword?key={{api_key}}
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}",
  "returnSecureToken": true
}

> {%
  client.global.set("token", response.body.idToken);
%}

### 必須 ユーザー情報を取得する。
GET http://{{endpoint}}/v1/users/mine
Content-Type: application/json
Authorization: Bearer {{token}}

> {%
  client.global.set("user_id", response.body.user.id);
%}

###　ユーザーを更新する。
PUT http://{{endpoint}}/v1/users/{{user_id}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "updated",
  "email": "updated",
  "image_url": "updated"
}

### 勤怠情報を取得する。
GET http://{{endpoint}}/v1/attendances?month=202005
Content-Type: application/json
Authorization: Bearer {{token}}

### 勤怠情報を取得する。
POST http://{{endpoint}}/v1/attendances
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "remark": "test"
}

### 勤怠情報のサマリーを取得する。
GET http://{{endpoint}}/v1/attendances/summary
Content-Type: application/json
Authorization: Bearer {{token}}
